add timeout
brentp/gargs pull request #6
Opened 2017-01-05 14:42 UTC by shenwei356

A timeout option added:

```
  --timeout TIMEOUT, -t TIMEOUT
                         timeout of a command. Unit is second and 0 with no timeout (default is 0).
```

Example:

No timeout:

```
$ time echo msg | ./gargs  'sleep 2; echo {}' 
msg

real    0m2.010s
user    0m0.003s
sys     0m0.008s
```

With timeout

```
$ time echo msg | ./gargs  'sleep 2; echo {}' -t 1
ERROR with command: Command('sleep 2; echo msg', stdout: '', exit-code: -1, error: signal: killed, run-time: 2.003461041s)

real    0m2.008s
user    0m0.006s
sys     0m0.002s
```
But the run-time is longer than the actual running time.

2017-01-05 15:38 UTC, brentp requested changes
This is great! Thank you.

Can you add a test to functional_tests.sh that does `sleep 10; echo "asdf"` with a timeout of 1 and make sure that there's no "asdf" in the output? Or something like that.

2017-01-05 15:59 UTC, shenwei356 commented
done!

2017-01-06 06:30 UTC, shenwei356 commented
Timeout works now !!!

No timeout:

```
$ time echo msg | ./gargs  'sleep 2; echo {}' 
msg

real    0m2.005s
user    0m0.004s
sys     0m0.001s
```

Timeout < running time

```
$ time echo msg | ./gargs  'sleep 2; echo {}' -t 1
ERROR with command: Command('sleep 2; echo msg', stdout: '', exit-code: 1, error: time out, run-time: 1.000322521s)

real    0m1.006s
user    0m0.004s
sys     0m0.004s
```

Timeout < running time, **and retry 2 times**

```
$ time echo msg | ./gargs  'sleep 2; echo {}' -t 1 -r 2
ERROR with command: Command('sleep 2; echo msg', stdout: '', exit-code: 1, error: time out, run-time: 3.001001931s)

real    0m3.006s
user    0m0.003s
sys     0m0.007s
```

Timeout > running time

```
$ time echo msg | ./gargs  'sleep 2; echo {}' -t 3
msg

real    0m2.010s
user    0m0.006s
sys     0m0.006s
```

2017-01-06 06:34 UTC, shenwei356 commented
Oh no! I'm fixing the `process_test.go`

2017-01-06 06:50 UTC, shenwei356 commented
Cheers! All tests passed! :smile: :smile: :smile:

2017-01-09 15:07 UTC, shenwei356 commented
Dear Brent, all tests passed, these commits can be merged now.

2017-01-09 16:07 UTC, brentp commented
I had a comment on here expressing my concerns about the added complexity and the leaking of goroutines but it seems to have been lost in the ether. I'm not sure this is worth it when it's simple to write a bash function that times out if a command doesn't finish within a certain time. 

Given that you seem to have done an entire rewrite (and then some) of gargs in your `rush` project, I suspect you'll be less inclined to maintain and contribute here so I'm even more hesitant to incorporate this code. 

I'm not decided on this, just expressing my concerns. Irrespective of that decision, in future projects, let's try to collaborate rather than replicate.

2017-01-09 17:06 UTC, shenwei356 commented
I understand your concern.

 It was a long time ago when I wanted write a tool like gargs and rush. But I did not find the right way of handling stdout of a process before knowing gargs. I used gargs to quicky solve a work which was not well done using parallel. The only missing feature is timeout, so I try to fork and contribute as I said and did. However I didn't follow your code so I decided to learn by practicing. rush is just a side product of my learning path, and it's a kind of complexed.

You'are my idol, I will be pleased to collaborate with you.

2017-01-09 17:19 UTC, brentp commented
agreed, it's definitely fun to create new stuff and sometimes you need custom features. I do appreciate you forking and adding the change, I'll leave this open for now.

want to collaborate on adding cram support to biogo/hts ? There's an issue open on that repo that I haven't made too much progress on that will be a lot of work.

2017-01-09 17:33 UTC, shenwei356 commented
that's a big challenge, i'll watch it. but my time is limited, cause it's the last semister of my phd learning.

2017-01-11 04:47 UTC, closed without merging

2017-07-28 14:43 UTC, brentp commented
I've been hitting the need for a timeout a lot lately. so I might resurrect this code and see if I can get it in.